// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/residwi/go-api-project-template/internal/features/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthManager creates a new instance of MockAuthManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockAuthManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockAuthManager is an autogenerated mock type for the AuthManager type
type MockAuthManager struct {
	mock.Mock
}

type MockAuthManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthManager) EXPECT() *MockAuthManager_Expecter {
	return &MockAuthManager_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthManager
func (_mock *MockAuthManager) Login(ctx context.Context, email string, password string) (*auth.TokenPair, error) {
	ret := _mock.Called(ctx, email, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *auth.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*auth.TokenPair, error)); ok {
		return returnFunc(ctx, email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *auth.TokenPair); ok {
		r0 = returnFunc(ctx, email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, email, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthManager_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthManager_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
func (_e *MockAuthManager_Expecter) Login(ctx any, email any, password any) *MockAuthManager_Login_Call {
	return &MockAuthManager_Login_Call{Call: _e.mock.On("Login", ctx, email, password)}
}

func (_c *MockAuthManager_Login_Call) Run(run func(ctx context.Context, email string, password string)) *MockAuthManager_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthManager_Login_Call) Return(tokenPair *auth.TokenPair, err error) *MockAuthManager_Login_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthManager_Login_Call) RunAndReturn(run func(ctx context.Context, email string, password string) (*auth.TokenPair, error)) *MockAuthManager_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Refresh provides a mock function for the type MockAuthManager
func (_mock *MockAuthManager) Refresh(ctx context.Context, refreshToken string) (*auth.TokenPair, error) {
	ret := _mock.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 *auth.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*auth.TokenPair, error)); ok {
		return returnFunc(ctx, refreshToken)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *auth.TokenPair); ok {
		r0 = returnFunc(ctx, refreshToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthManager_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type MockAuthManager_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthManager_Expecter) Refresh(ctx any, refreshToken any) *MockAuthManager_Refresh_Call {
	return &MockAuthManager_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *MockAuthManager_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthManager_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthManager_Refresh_Call) Return(tokenPair *auth.TokenPair, err error) *MockAuthManager_Refresh_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthManager_Refresh_Call) RunAndReturn(run func(ctx context.Context, refreshToken string) (*auth.TokenPair, error)) *MockAuthManager_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockAuthManager
func (_mock *MockAuthManager) Register(ctx context.Context, email string, password string, firstName string, lastName string) (*auth.TokenPair, error) {
	ret := _mock.Called(ctx, email, password, firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *auth.TokenPair
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*auth.TokenPair, error)); ok {
		return returnFunc(ctx, email, password, firstName, lastName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) *auth.TokenPair); ok {
		r0 = returnFunc(ctx, email, password, firstName, lastName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, password, firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthManager_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockAuthManager_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - password string
//   - firstName string
//   - lastName string
func (_e *MockAuthManager_Expecter) Register(ctx any, email any, password any, firstName any, lastName any) *MockAuthManager_Register_Call {
	return &MockAuthManager_Register_Call{Call: _e.mock.On("Register", ctx, email, password, firstName, lastName)}
}

func (_c *MockAuthManager_Register_Call) Run(run func(ctx context.Context, email string, password string, firstName string, lastName string)) *MockAuthManager_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockAuthManager_Register_Call) Return(tokenPair *auth.TokenPair, err error) *MockAuthManager_Register_Call {
	_c.Call.Return(tokenPair, err)
	return _c
}

func (_c *MockAuthManager_Register_Call) RunAndReturn(run func(ctx context.Context, email string, password string, firstName string, lastName string) (*auth.TokenPair, error)) *MockAuthManager_Register_Call {
	_c.Call.Return(run)
	return _c
}
