all: false
dir: "mocks/{{.SrcPackageName}}"
filename: "mock_{{.InterfaceName}}.go"
force-file-write: true
formatter: goimports
log-level: info
pkgname: "mocks"
template: testify
packages:
  github.com/residwi/go-api-project-template/internal/features/auth:
    interfaces:
      UserProvider:
  github.com/residwi/go-api-project-template/internal/features/user:
    interfaces:
      Repository:
  github.com/residwi/go-api-project-template/internal/middleware:
    interfaces:
      TokenValidator:
      UserStatusChecker:
