// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package http

import (
	"context"

	"github.com/google/uuid"
	"github.com/residwi/go-api-project-template/internal/features/user"
	"github.com/residwi/go-api-project-template/internal/features/user/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserManager creates a new instance of MockUserManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockUserManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockUserManager is an autogenerated mock type for the UserManager type
type MockUserManager struct {
	mock.Mock
}

type MockUserManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserManager) EXPECT() *MockUserManager_Expecter {
	return &MockUserManager_Expecter{mock: &_m.Mock}
}

// AdminUpdate provides a mock function for the type MockUserManager
func (_mock *MockUserManager) AdminUpdate(ctx context.Context, id uuid.UUID, firstName string, lastName string, phone *string, active *bool) (*domain.User, error) {
	ret := _mock.Called(ctx, id, firstName, lastName, phone, active)

	if len(ret) == 0 {
		panic("no return value specified for AdminUpdate")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *string, *bool) (*domain.User, error)); ok {
		return returnFunc(ctx, id, firstName, lastName, phone, active)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *string, *bool) *domain.User); ok {
		r0 = returnFunc(ctx, id, firstName, lastName, phone, active)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, *string, *bool) error); ok {
		r1 = returnFunc(ctx, id, firstName, lastName, phone, active)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserManager_AdminUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdminUpdate'
type MockUserManager_AdminUpdate_Call struct {
	*mock.Call
}

// AdminUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - firstName string
//   - lastName string
//   - phone *string
//   - active *bool
func (_e *MockUserManager_Expecter) AdminUpdate(ctx any, id any, firstName any, lastName any, phone any, active any) *MockUserManager_AdminUpdate_Call {
	return &MockUserManager_AdminUpdate_Call{Call: _e.mock.On("AdminUpdate", ctx, id, firstName, lastName, phone, active)}
}

func (_c *MockUserManager_AdminUpdate_Call) Run(run func(ctx context.Context, id uuid.UUID, firstName string, lastName string, phone *string, active *bool)) *MockUserManager_AdminUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *bool
		if args[5] != nil {
			arg5 = args[5].(*bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockUserManager_AdminUpdate_Call) Return(user *domain.User, err error) *MockUserManager_AdminUpdate_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserManager_AdminUpdate_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, firstName string, lastName string, phone *string, active *bool) (*domain.User, error)) *MockUserManager_AdminUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockUserManager
func (_mock *MockUserManager) Delete(ctx context.Context, requesterID uuid.UUID, targetID uuid.UUID) error {
	ret := _mock.Called(ctx, requesterID, targetID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, requesterID, targetID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserManager_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockUserManager_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - targetID uuid.UUID
func (_e *MockUserManager_Expecter) Delete(ctx any, requesterID any, targetID any) *MockUserManager_Delete_Call {
	return &MockUserManager_Delete_Call{Call: _e.mock.On("Delete", ctx, requesterID, targetID)}
}

func (_c *MockUserManager_Delete_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, targetID uuid.UUID)) *MockUserManager_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserManager_Delete_Call) Return(err error) *MockUserManager_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserManager_Delete_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, targetID uuid.UUID) error) *MockUserManager_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockUserManager
func (_mock *MockUserManager) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserManager_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockUserManager_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserManager_Expecter) GetByID(ctx any, id any) *MockUserManager_GetByID_Call {
	return &MockUserManager_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockUserManager_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserManager_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserManager_GetByID_Call) Return(user *domain.User, err error) *MockUserManager_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserManager_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.User, error)) *MockUserManager_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListAdmin provides a mock function for the type MockUserManager
func (_mock *MockUserManager) ListAdmin(ctx context.Context, params user.AdminListParams) ([]domain.User, int, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAdmin")
	}

	var r0 []domain.User
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.AdminListParams) ([]domain.User, int, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.AdminListParams) []domain.User); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user.AdminListParams) int); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, user.AdminListParams) error); ok {
		r2 = returnFunc(ctx, params)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUserManager_ListAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAdmin'
type MockUserManager_ListAdmin_Call struct {
	*mock.Call
}

// ListAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - params user.AdminListParams
func (_e *MockUserManager_Expecter) ListAdmin(ctx any, params any) *MockUserManager_ListAdmin_Call {
	return &MockUserManager_ListAdmin_Call{Call: _e.mock.On("ListAdmin", ctx, params)}
}

func (_c *MockUserManager_ListAdmin_Call) Run(run func(ctx context.Context, params user.AdminListParams)) *MockUserManager_ListAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.AdminListParams
		if args[1] != nil {
			arg1 = args[1].(user.AdminListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserManager_ListAdmin_Call) Return(users []domain.User, n int, err error) *MockUserManager_ListAdmin_Call {
	_c.Call.Return(users, n, err)
	return _c
}

func (_c *MockUserManager_ListAdmin_Call) RunAndReturn(run func(ctx context.Context, params user.AdminListParams) ([]domain.User, int, error)) *MockUserManager_ListAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRole provides a mock function for the type MockUserManager
func (_mock *MockUserManager) UpdateRole(ctx context.Context, requesterID uuid.UUID, targetID uuid.UUID, role string) error {
	ret := _mock.Called(ctx, requesterID, targetID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, requesterID, targetID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserManager_UpdateRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRole'
type MockUserManager_UpdateRole_Call struct {
	*mock.Call
}

// UpdateRole is a helper method to define mock.On call
//   - ctx context.Context
//   - requesterID uuid.UUID
//   - targetID uuid.UUID
//   - role string
func (_e *MockUserManager_Expecter) UpdateRole(ctx any, requesterID any, targetID any, role any) *MockUserManager_UpdateRole_Call {
	return &MockUserManager_UpdateRole_Call{Call: _e.mock.On("UpdateRole", ctx, requesterID, targetID, role)}
}

func (_c *MockUserManager_UpdateRole_Call) Run(run func(ctx context.Context, requesterID uuid.UUID, targetID uuid.UUID, role string)) *MockUserManager_UpdateRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserManager_UpdateRole_Call) Return(err error) *MockUserManager_UpdateRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserManager_UpdateRole_Call) RunAndReturn(run func(ctx context.Context, requesterID uuid.UUID, targetID uuid.UUID, role string) error) *MockUserManager_UpdateRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProfileManager creates a new instance of MockProfileManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProfileManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProfileManager {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockProfileManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockProfileManager is an autogenerated mock type for the ProfileManager type
type MockProfileManager struct {
	mock.Mock
}

type MockProfileManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProfileManager) EXPECT() *MockProfileManager_Expecter {
	return &MockProfileManager_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockProfileManager
func (_mock *MockProfileManager) GetByID(ctx context.Context, id uuid.UUID) (*domain.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileManager_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProfileManager_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockProfileManager_Expecter) GetByID(ctx any, id any) *MockProfileManager_GetByID_Call {
	return &MockProfileManager_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProfileManager_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockProfileManager_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProfileManager_GetByID_Call) Return(user1 *domain.User, err error) *MockProfileManager_GetByID_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockProfileManager_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*domain.User, error)) *MockProfileManager_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProfile provides a mock function for the type MockProfileManager
func (_mock *MockProfileManager) UpdateProfile(ctx context.Context, id uuid.UUID, firstName string, lastName string, phone *string) (*domain.User, error) {
	ret := _mock.Called(ctx, id, firstName, lastName, phone)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfile")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *string) (*domain.User, error)); ok {
		return returnFunc(ctx, id, firstName, lastName, phone)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, *string) *domain.User); ok {
		r0 = returnFunc(ctx, id, firstName, lastName, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, *string) error); ok {
		r1 = returnFunc(ctx, id, firstName, lastName, phone)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProfileManager_UpdateProfile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProfile'
type MockProfileManager_UpdateProfile_Call struct {
	*mock.Call
}

// UpdateProfile is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - firstName string
//   - lastName string
//   - phone *string
func (_e *MockProfileManager_Expecter) UpdateProfile(ctx any, id any, firstName any, lastName any, phone any) *MockProfileManager_UpdateProfile_Call {
	return &MockProfileManager_UpdateProfile_Call{Call: _e.mock.On("UpdateProfile", ctx, id, firstName, lastName, phone)}
}

func (_c *MockProfileManager_UpdateProfile_Call) Run(run func(ctx context.Context, id uuid.UUID, firstName string, lastName string, phone *string)) *MockProfileManager_UpdateProfile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockProfileManager_UpdateProfile_Call) Return(user1 *domain.User, err error) *MockProfileManager_UpdateProfile_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockProfileManager_UpdateProfile_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, firstName string, lastName string, phone *string) (*domain.User, error)) *MockProfileManager_UpdateProfile_Call {
	_c.Call.Return(run)
	return _c
}
